# Generated by Django 3.2 on 2021-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stududents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(null=True)),
                ('roll_no', models.IntegerField(null=True)),
                ('adress', models.CharField(max_length=500, null=True)),
                ('semester', models.CharField(choices=[('1stsem', '1stsem'), ('2stsem', '2stsem'), ('3stsem', '3stsem'), ('4stsem', '4stsem'), ('5stsem', '5stsem'), ('6stsem', '6stsem')], max_length=200, null=True)),
            ],
        ),
    ]
