# Generated by Django 3.2 on 2021-04-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stududents',
            new_name='Stududent',
        ),
    ]
