# Generated by Django 3.2 on 2021-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_stududents_stududent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stududent',
            new_name='Student',
        ),
    ]
